# Generated by Django 3.2 on 2021-04-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitconv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='conversion_factor',
            field=models.FloatField(),
        ),
    ]
