# Generated by Django 3.2 on 2021-04-15 23:59

from django.db import migrations

factors = {
    "oz": 1 / 35.274,
    "T": 1 / 0.00098421,
    "g": 1 / 1000,
    "lb": 1 / 2.2046,
    "t_oz": 1 / 32.151,
    "kg": 1,
}


def create_conversions(apps, schema_editor):
    Conversion = apps.get_model("unitconv", "Conversion")
    for key, value in factors.items():
        c = Conversion(from_unit=key, to_unit="kg", conversion_factor=value)
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ("unitconv", "0002_alter_conversion_conversion_factor"),
    ]

    operations = [migrations.RunPython(create_conversions)]
