#! /bin/bash

set -e

java="/usr/lib/jvm/java-19-openjdk/bin/java"

compile=false
if [ $1 == "-c" ]
then
  compile=true
  shift
fi

echo "Running Tests"
$compile && echo "Compiling before running"

if [ $1 == "all" ]
then
  for i in {1..14}
  do
    echo "Running test$i.asm"
    $compile && $java -cp ../out/production/p5-compiler:../antlr-4.9.1-complete.jar main.Main ./test$i.c
    $java -jar ./Mars4_5.jar ./test$i.asm
  done
else
    $compile && $java -cp ../out/production/p5-compiler:../antlr-4.9.1-complete.jar main.Main ./test$1.c
    $java -jar ./Mars4_5.jar ./test$1.asm
fi

